Path = "/home/qmiao/Desktop/n3/n3-privacy/Server/config/temp.toml"
LogFile = "./N3-PRIVACY-2020-06-25.log"
ServiceName = "N3-PRIVACY"

[Route]
  HELP = "/"
  GetID = "/policy-service/0.1.0/id"
  GetHash = "/policy-service/0.1.0/hash"
  Get = "/policy-service/0.1.0/policy"
  Update = "/policy-service/0.1.0/update"
  Delete = "/policy-service/0.1.0/delete"
  LsID = "/policy-service/0.1.0/list/policyid"
  LsUser = "/policy-service/0.1.0/list/user"
  LsContext = "/policy-service/0.1.0/list/context"
  LsObject = "/policy-service/0.1.0/list/object"
  Enforce = "/policy-service/0.1.0/enforce"

[Server]
  Protocol = "http"
  IP = "192.168.31.168"
  Port = 1323

[Access]
  Timeout = 3
